"""simplify_roles_remove_system_admin

Revision ID: 88f5ab88de5f
Revises: e9cfb1700953
Create Date: 2025-10-20 19:38:16.510026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88f5ab88de5f'
down_revision: Union[str, None] = 'e9cfb1700953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
