"""add_application_access_control_and_permissions

Revision ID: e9cfb1700953
Revises: 1a517bce7069
Create Date: 2025-10-20 18:55:51.273557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9cfb1700953'
down_revision: Union[str, None] = '1a517bce7069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_name', sa.String(), nullable=False),
    sa.Column('allowed_roles', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_name')
    )
    op.create_table('module_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('module_category', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'PATIENT', 'ADMIN', 'PHYSICIAN', 'NUTRITIONIST', 'NURSE', 'SYSTEM_ADMIN', name='userrole'), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name', 'role', name='uq_module_role')
    )
    op.create_index(op.f('ix_module_permissions_role'), 'module_permissions', ['role'], unique=False)
    op.add_column('users', sa.Column('primary_application', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'profile_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'journey_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.alter_column('users', 'journey_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'profile_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'primary_application')
    op.drop_index(op.f('ix_module_permissions_role'), table_name='module_permissions')
    op.drop_table('module_permissions')
    op.drop_table('application_access')
    # ### end Alembic commands ###
